### ISSUE TITLE
[Feature] 不支持行内语法实时渲染

### ISSUE THREAD

**Issue by xygengcn** [syfxlin/tiptap-starter-kit#22]
如果是在新的一行开始加粗、斜体、code等语法是支持的，如果在一行已经编辑好的文字，不使用menu加粗，直接用**包裹是无法实现渲染

![屏幕录制2024-06-26 16 47 06](https://github.com/syfxlin/tiptap-starter-kit/assets/35959814/e21c8905-be9d-40da-9c6a-6e34686115a3)

**Comment by syfxlin** [comment]
Hi @xygengcn，这个问题是 Tiptap Bold 提供的输入规则导致的，Tiptap Bold 扩展要求粗体第一个 `**` 前需要存在空白字符或是段落开始。可以通过覆盖默认的输入规则修复，下次更新会修复。
