### ISSUE TITLE
emoji唤出的bug

### ISSUE THREAD

**Issue by DylanZella** [syfxlin/tiptap-starter-kit#3]
#### 复现流程：
当输入`::`时可以唤醒emoji，当继续输入的内容中含有``::``时会触发bug

比如以下内容：
```
::abcdas::sadaas
```

bug截图

![image](https://user-images.githubusercontent.com/27148578/223973501-b49792ab-204e-4abc-9943-ce1f9c5d305a.png)

@syfxlin  期待着您抽空修复，Thanks

**Comment by syfxlin** [comment]
Hi @DylanZella，感谢报告这个问题，近期有计划对组件进行改造，届时会一并修复这个问题，Thanks。
