### ISSUE TITLE
Do you have any plans to upgrade the version of tiptap?

### ISSUE THREAD

**Issue by kobe651jp** [syfxlin/tiptap-starter-kit#30]
The latest version of tiptap is 2.5.4.

If you can upgrade it, please do so.
I would like to fork it into a Japanese version and incorporate it into my application.

This starter kit is great.

Thanks.

**Comment by syfxlin** [comment]
No problem, I will be upgrading tiptap to 2.5.4 soon.

Also, this kit has options reserved for i18n, you may consider using them for localization, thanks.

https://github.com/syfxlin/tiptap-starter-kit/blob/53232acf5719c0192a2fbb1530cae20b128afc2f/src/marks/bold.ts#L12-L16

**Comment by kobe651jp** [comment]
Thank you very much. I appreciate it.
