### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by clibu** [syfxlin/tiptap-starter-kit#35]
Thanks for your great starter kit. 

What is missing is documentation for each of the Extensions. Is that coming?

Is React required to use these extensions. Hopefully not. I see the Demo app uses React.

Will this work alongside TipTap Starter kit and TipTap Extensions or are they mutually exclusive?

Also do all of the extensions work with Hocuspocus on the server? Where/how are video and audio files stored?

**Comment by syfxlin** [comment]
There's no documentation at the moment, and I plan to finish writing it by September.

Extensions do not need to use React, you can use any framework supported by Tiptap.

You can add any Tiptap extension, they should not be incompatible. In fact, most of the extensions in this starter kit are extended from the official Tiptap extensions.

Video and audio files are uploaded using the Uploader extension, which by default encodes the file as a data url embedded in the content. https://github.com/syfxlin/tiptap-starter-kit/blob/master/src/extensions/uploader/index.ts#L32-L54

I have not tried Hocuspocus and am unsure if it will work properly with this starter kit. You can try it and if you encounter any problems, you can report them here.

Thanks.

**Comment by clibu** [comment]
@syfxlin Thanks for the reply. Looking forward to seeing the Docs etc. I'll let you know if I have any issues.
