### ISSUE TITLE
[QUESTION] How to add more items to the block menu?

### ISSUE THREAD

**Issue by thednp** [syfxlin/tiptap-starter-kit#42]
First: thank you for your work, much appreciated. I know Docs is in the works but still wish to know asap.

I've added some more more heading tags, but I can't seem to add something else. I'm trying to add some sort of columns via [this guide](https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/examples#drag-handles).

How ca we add more items to the block menu please?

What those items are supposed to be? Nodes? Config parts?

Can you please make a super quick example?

Thank you so much :rocket:

**Comment by syfxlin** [comment]
Hi @thednp,

If you want to configure the block menu for the new extension, you need to add some configuration in storage, you can refer to [blockquote extension](https://github.com/syfxlin/tiptap-starter-kit/blob/master/src/nodes/blockquote.ts#L43-L54), [TypeScript definitions](https://github.com/syfxlin/tiptap-starter-kit/blob/master/src/extensions/block-menu/menu.ts#L7-L14).

Then you need to configure the [block menu extension options](https://github.com/syfxlin/tiptap-starter-kit/blob/master/src/extensions/block-menu/menu.ts#L36-L59) (See the Usage section of the README for how to configure options) by placing the [new extension id](https://github.com/syfxlin/tiptap-starter-kit/blob/master/src/nodes/blockquote.ts#L46) where you think it should be, please note that the order in which the menus will be displayed will be determined by this order.
